# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 15:41
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='轮播图片', upload_to='banner', verbose_name='轮播图片')),
                ('index', models.IntegerField(default=0, help_text='轮播排序', verbose_name='轮播排序')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2018, 11, 16, 23, 41, 55, 373950), help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播商品',
                'verbose_name_plural': '轮播商品',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_sn', models.CharField(default='', help_text='商品唯一货号', max_length=50, verbose_name='商品唯一货号')),
                ('name', models.CharField(help_text='商品名', max_length=100, verbose_name='商品名')),
                ('click_num', models.IntegerField(default=0, help_text='点击数', verbose_name='点击数')),
                ('sold_num', models.IntegerField(default=0, help_text='销售量', verbose_name='销售量')),
                ('fav_num', models.IntegerField(default=0, help_text='收藏数', verbose_name='收藏数')),
                ('goods_num', models.IntegerField(default=0, help_text='库存数', verbose_name='库存数')),
                ('market_price', models.FloatField(default=0, help_text='市场价格', verbose_name='市场价格')),
                ('shop_price', models.FloatField(default=0, help_text='本店价格', verbose_name='本店价格')),
                ('goods_brief', models.TextField(help_text='商品简短描述', max_length=500, verbose_name='商品简短描述')),
                ('goods_desc', DjangoUeditor.models.UEditorField(default='', help_text='商品内容', verbose_name='商品内容')),
                ('ship_free', models.BooleanField(default=True, help_text='是否承担运费', verbose_name='是否承担运费')),
                ('goods_front_image', models.ImageField(blank=True, help_text='封面图', null=True, upload_to='goods/iamges/', verbose_name='封面图')),
                ('is_new', models.BooleanField(default=False, help_text='是否新品', verbose_name='是否新品')),
                ('is_hot', models.BooleanField(default=False, help_text='是否热销', verbose_name='是否热销')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2018, 11, 16, 23, 41, 55, 369950), help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code')),
                ('desc', models.CharField(default='', help_text='类别描述', max_length=300, verbose_name='类别描述')),
                ('category_type', models.CharField(choices=[(1, '一级分类'), (2, '二级分类'), (3, '三级分类')], help_text='类别类型', max_length=10, verbose_name='类别类型')),
                ('is_tab', models.BooleanField(default=False, help_text='是否导航', verbose_name='是否导航')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2018, 11, 16, 23, 41, 55, 366950), help_text='添加时间', verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父类别', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.GoodsCategory', verbose_name='父类')),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='品牌名', max_length=30, verbose_name='品牌名')),
                ('desc', models.CharField(default='', help_text='品牌描述', max_length=30, verbose_name='品牌描述')),
                ('image', models.ImageField(help_text='上传图片', max_length=200, upload_to='brands/images/', verbose_name='上传图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2018, 11, 16, 23, 41, 55, 368950), help_text='添加时间', verbose_name='添加时间')),
                ('category', models.ForeignKey(help_text='商品类目', on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类目')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2018, 11, 16, 23, 41, 55, 371950), help_text='添加时间', verbose_name='添加时间')),
                ('goods', models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品轮播图',
                'verbose_name_plural': '商品轮播图',
            },
        ),
        migrations.CreateModel(
            name='HotSearchWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default='', help_text='热搜词', max_length=20, verbose_name='热搜词')),
                ('index', models.IntegerField(default=0, help_text='排序', verbose_name='排序')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2018, 11, 16, 23, 41, 55, 376950), help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '热搜词',
                'verbose_name_plural': '热搜词',
            },
        ),
        migrations.CreateModel(
            name='IndexAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='goods.GoodsCategory', verbose_name='商品类目')),
                ('goods', models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '首页商品类别广告',
                'verbose_name_plural': '首页商品类别广告',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(help_text='商品类目', on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类目'),
        ),
        migrations.AddField(
            model_name='banner',
            name='goods',
            field=models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品'),
        ),
    ]
