# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 20:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20181117_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPriceRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_min', models.FloatField(default=0, help_text='最小价格', verbose_name='最小价格')),
                ('price_max', models.FloatField(help_text='最大价格', verbose_name='最大价格')),
                ('index', models.IntegerField(default=0, help_text='排序', verbose_name='排序')),
            ],
            options={
                'verbose_name': '分类搜索价格区间',
                'verbose_name_plural': '分类搜索价格区间',
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 20, 34, 49, 548832), help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 20, 34, 49, 545831), help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 20, 34, 49, 542831), help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='category_type',
            field=models.IntegerField(choices=[(1, '一级分类'), (2, '二级分类'), (3, '三级分类')], help_text='类别类型', max_length=10, verbose_name='类别类型'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='父类别', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categorys', to='goods.GoodsCategory', verbose_name='父类'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 20, 34, 49, 544831), help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 20, 34, 49, 547831), help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='hotsearchwords',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 20, 34, 49, 550832), help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='searchpricerange',
            name='category',
            field=models.ForeignKey(help_text='商品类目', on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类目'),
        ),
    ]
