# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 09:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20181203_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 4, 9, 42, 7, 100424), help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 4, 9, 42, 7, 98424), help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 4, 9, 42, 7, 95424), help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 4, 9, 42, 7, 97424), help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 4, 9, 42, 7, 99424), help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='hotsearchwords',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 4, 9, 42, 7, 102424), help_text='添加时间', verbose_name='添加时间'),
        ),
    ]
