# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20181220_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='category_type',
            field=models.IntegerField(choices=[(1, '一级分类'), (2, '二级分类'), (3, '三级分类')], help_text='类别类型', verbose_name='类别类型'),
        ),
    ]
