# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20181117_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': '收货地址', 'verbose_name_plural': '收货地址'},
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 17, 11, 21, 26, 540960), help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userfav',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 17, 11, 21, 26, 537959), help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 17, 11, 21, 26, 538959), help_text='添加时间', verbose_name='添加时间'),
        ),
    ]
