# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-24 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0007_auto_20181223_1309'),
        ('user_operation', '0005_auto_20181220_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleavingmessage',
            name='message',
            field=models.CharField(default='', help_text='留言内容', max_length=500, verbose_name='留言内容'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='subject',
            field=models.CharField(default='', help_text='留言内容', max_length=100, verbose_name='主题'),
        ),
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together=set([('user', 'goods')]),
        ),
    ]
